#!/bin/bash

if [ ! -d ${QN_NOTES_FOLDER} ]; then
  exit 0
fi

#search in notes
slashes=${QN_NOTES_FOLDER//[!\/]}
depth=$(( ${#slashes} + 2 ))
files=$(find ${QN_NOTES_FOLDER} | grep ".txt" | cut -d'/' -f${depth}- | grep --color=always $1)

if [ -z "${files}" ]; then
  exit 0
fi

while read -r file; do
  echo $file
  file_no_color=$(sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2};?)?)?[mGK]//g" <<< ${file})
  cat "${QN_NOTES_FOLDER}/$file_no_color" | sed 's/\(.*\)/\t\1/'
done <<< "$files"