#!/bin/bash

if [ ! -d ${QN_NOTES_FOLDER} ]; then
  exit 0
fi

#search in notes
# TODO: don't know how to remove path prefix
#       to awoid serch in it
files=$(find ${QN_NOTES_FOLDER} | grep ".txt" | sed 's/.*\(_notes\)//g' | grep --color=always $1)

if [ -z "${files}" ]; then
  exit 0
fi

while read -r file; do
  echo $file
  file_no_color=$(sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2};?)?)?[mGK]//g" <<< ${file})
  cat "${QN_NOTES_FOLDER}/$file_no_color" | sed 's/\(.*\)/\t\1/'
done <<< "$files"