#!/bin/bash

. ${QN_SRC_FOLDER}/notes/utils

if [ $# -eq 0 ]; then
  echo "error: note hint required"
  exit 1
fi

if [ ! -d ${QN_NOTES_FOLDER} ]; then
  exit 0
fi

slashes=${QN_NOTES_FOLDER//[!\/]}
depth=${#slashes}

files=$(find ${QN_NOTES_FOLDER} | grep ".txt" | cut -d'/' -f${depth}- | grep --color=always $1)
if [ -z "${files}" ]; then
  echo "no match"
  exit 0
fi

substr="$1"
line_count=$(echo "$files" | wc -l)

while [ ${line_count} -ne 1 ]; do
  if [ -n "${files}" ]; then
    echo "${files}"
  fi
  read -p "Specify note: " substr
  
  files=$(find ${QN_NOTES_FOLDER} | grep ".txt" | cut -d'/' -f${depth}- | grep --color=always ${substr})

  if [ -z "${files}" ]; then
    line_count=0
  else
    line_count=$(echo "${files}" | wc -l)
  fi

done

target=$(find ${QN_NOTES_FOLDER} | grep ".txt" | grep ${substr})
nano ${target}
