#!/bin/bash

# quick note create

. __qn_utils

check_data_dir

if [ -z "$1" ]; then
  echo -e "error: option is required. 
try: qn --help"
  exit 1
fi

if [ "$1" = "--create" ] || [ "$1" = "-c" ]; then
  shift
  qnc "$@"
  exit 0
fi

if [ "$1" = "--read" ] || [ "$1" = "-r" ]; then
  shift
  qnr "$@"
  exit 0
fi

if [ "$1" = "--delete" ] || [ "$1" = "-d" ]; then
  shift
  qnd "$@"
  exit 0
fi

if [ "$1" = "--update" ] || [ "$1" = "-u" ]; then
  shift
  qnu "$@"
  exit 0
fi

if [ "$1" = "--tree" ] || [ "$1" = "-t" ]; then
  check_named
  cd ${QN_NAMED_DIR}
  tree . | head -n -2
  exit 0
fi

if [ "$1" = "--all" ] || [ "$1" = "-a" ]; then
  unnamed_exists
  if [ "$?" -eq 0 ] ; then
    cat ${QN_UNNAMED}
  fi
  named_exists
  if [ "$?" -eq 0 ] ; then
    all_named_notes
  fi
  exit 0;
  // TODO: echo empty if empty
fi

if [ "$1" = "update" ]; then
  cd ${QN_DATA_SRC}
  git pull
  exit 0;
fi

if [ "$1" = "--help" ]|| [ "$1" = "-h" ]; then
  echo -e "
  Usage: qn OPTION [TITLE]
  <title_hint> is any part of title or sequence of title parts.

  -c, --create  <title>         CREATE note with title.     qnc for short.
  -r, --read    <title_hint>    READ   note by title hint.  qnr for short.
  -d, --delete  <title_hint>    DELETE note by title hint.  qnr for short.
  -u, --update  <title_hint>    UPDATE note by title hint.  qnu for short.

  -a, --all                     list of notes.
  -t, --tree                    tree structure of notes.

  -h, --help                    qnotes manual
  update                        update qnotes
"
  exit 0;
fi

echo "error: invalid option"
