#!/bin/bash

# quick note read

. __qn_utils

check_data_dir
check_hint "$*"
check_all

regexp=$(regexp_hint "$*")

#search in unnamed notes
if [ -f ${QN_UNNAMED} ]; then
  cat ${QN_UNNAMED} | grep --color=always ${regexp}
fi


#search in named notes
if [ ! -d ${QN_NAMED_DIR} ]; then
  exit 0
fi

files=$(find_named_notes $regexp --color=always)

if [ -z "${files}" ]; then
  exit 0
fi

while read -r file; do
  echo "$file"
  file_no_color=$(remove_color ${file})
  cat "${QN_NAMED_DIR}/$file_no_color" | sed 's/\(.*\)/\t\1/'
done <<< "$files"

