#!/bin/bash

# quick note tree

if [ -z "${QN_FOLDER}" ]; then
  echo "error: QN_FOLDER is undefined"
  exit 0
fi

. ${QN_FOLDER}/qn_config

if [ -d ${QN_NOTES_FOLDER} ]; then
  cd ${QN_NOTES_FOLDER}
  tree .
fi