#!/bin/bash

# quick note update

. __qn_utils

check_data_dir
check_hint "$*"

__target=""
find_target "$*"
unnamed=$(grep "$__target" $QN_UNNAMED)

if [ -n "$unnamed" ]; then
  echo "$__target" > $QN_TMP
  nano $QN_TMP
  new_line=$(head -n 1 < $QN_TMP)
  cat $QN_UNNAMED | sed -e "s/$__target/$new_line/" > $QN_TMP && mv $QN_TMP $QN_UNNAMED
else
  nano $QN_NAMED_DIR/"$__target"
fi

